### PR TITLE
Migrate to jpm & add Pale Moon support

### LINKED ISSUE #1: [REJECTED] Pale Moon support
Dear @aeris, your extension is based on Jetpack which makes it [incompatible](https://forum.palemoon.org/viewtopic.php?t=8740) with [Pale Moon](https://www.palemoon.org/roadmap.shtml), the most promising fork of Firefox out there. However [it welcomes XUL](https://www.palemoon.org/dev/addon-sdk/). Could you explore the possibility of supporting the broader reading audience, including Pale Moon users?

### PR DESCRIPTION
**Pull request by JustOff**
Resolves #1 based on [PMkit documentation draft](https://github.com/JustOff/pm27-sdk-addons/blob/master/PMkit.md).

Makefile wasn't updated to `jpm`, but manual build using `jpm xpi` verified.

### CODE REVIEW

**Comment by JustOff** [comment]
Since there was no reply for three months, I'm going to release my fork as a new add-on.

**Comment by aeris** [comment]
Oh, sorry, I didn't see your PR… /o\\
Will look quickly to release a new version.

**Comment by JustOff** [comment]
It would be very kind of you, see [here](https://forum.palemoon.org/viewtopic.php?p=113527#p113527).

**Comment by aeris** [comment]
Release done this day.
Waiting for Mozilla for publication, but extension is [here](https://github.com/aeris/enjoy-reading/releases/download/3.0.2/enjoy-reading.xpi) too if needed.

**Pull request closed without merging**
